### ISSUE TITLE
detect if we are piping to a file and do not pop console if so at end

### ISSUE THREAD

**Issue by brandonros** [sha0coder/scemu#20]
leads to awkward behavior in my opinion

**Comment by brandonros** [comment]
also detect if we are piping to file and auto add no-colors

**Comment by sha0coder** [comment]
one option is if you select --nocolors or -n  disable automatically the console, because is going to do a grep or a piping a file.

**Comment by sha0coder** [comment]
if stdout is redirected to a file or it's grepped is a thing that cannot be detected from the program I think.

**Comment by brandonros** [comment]
https://unix.stackexchange.com/questions/515778/how-does-a-program-know-if-stdout-is-connected-to-a-terminal-or-a-pipe

**Comment by brandonros** [comment]
https://docs.rs/atty/latest/atty/

**Comment by sha0coder** [comment]
perfect, i tried atty and work ok.

**Comment by sha0coder** [comment]
nice idea, done.
