### ISSUE TITLE
lahf broken

### ISSUE THREAD

**Issue by brandonros** [sha0coder/scemu#28]
```
{
    "i": 43,
    "x64dbgLine": {
      "rawLine": {
        "Index": "0002B",
        "Address": "0000000144FF9577",
        "Bytes": "9F",
        "Disassembly": "lahf ",
        "Registers": "rax: 0-> 200",
        "Memory": "",
        "Comments": ""
      },
      "rip": "144ff9577",
      "registerChanges": [
        {
          "registerName": "rax",
          "previousValue": "0",
          "newValue": "200"
        }
      ],
      "memoryChanges": []
    },
    "scemuLine": {
      "rawLine": "diff_reg: rip = 144ff9577 rax 0 -> 400;",
      "rip": "144ff9577",
      "registerChanges": [
        {
          "registerName": "rax",
          "previousValue": "0",
          "newValue": "400"
        }
      ],
      "memoryChanges": []
    },
    "instructionErrors": [
      {
        "index": 0,
        "message": "newValue mismatch",
        "x64dbg": "200",
        "scemu": "400"
      },
      {
        "index": 0,
        "message": "newValue mismatch",
        "x64dbg": "200",
        "scemu": "400"
      }
    ]
  },
```

**Comment by brandonros** [comment]
![image](https://user-images.githubusercontent.com/8949910/193292385-46ddaf8d-9c49-4221-9f90-8f8b6d749a14.png)

```
44 0x144ff9577: lahf
lahf: zf = 0
lahf: pf = 1
lahf: af = 0
lahf: of = 0
lahf: sf = 0
lahf: df = 0
lahf: cf = 0
lahf: tf = 0
lahf: if = 0
```

we have pf 0, it should be 1

x64dbg has tf 1, we have 0

x64dbg has if 1, we have 0

**Comment by brandonros** [comment]
lahf: `// Load: AH := EFLAGS(SF:ZF:0:AF:0:PF:1:CF).` https://www.felixcloutier.com/x86/lahf

**Comment by brandonros** [comment]
```rust
use bitvec::prelude::*;

fn main() {
    let f_zf = false;
    let f_pf = false;
    let f_af = false;

    let f_of = false;
    let f_sf = false;
    let f_df = false;

    let f_cf = false;
    let f_tf = true;
    let f_if = true;
  
    let mut bit_array: BitArray<[u8; 8], Msb0> = BitArray::ZERO;
    bit_array.set(0, f_sf);
    bit_array.set(1, f_zf);
    bit_array.set(2, false);
    bit_array.set(3, f_af);
    bit_array.set(4, false);
    bit_array.set(5, f_pf);
    bit_array.set(6, true);
    bit_array.set(7, f_cf);
    let output: u8 = bit_array.load();
    println!("{:x}", output);
}
```

i was trying to get this going to match x64dbg but having some issues (they don't match lol)

**Comment by sha0coder** [comment]
```
44 0x144ff9577: lahf
--- console ---
=>f
--- flags ---
cf: false
pf: true         --> not enabled on x64dbg
af: false
zf: false
sf: false
tf: false      --> enabled on x64dbg
if: false      --> enabled on x64dbg
df: false
of: false
nt: false
```

if and tf don't affect "directly" on the execution flow.

**Comment by sha0coder** [comment]
i would be nice to trace&diff the flags, is the base of the emulation.

**Comment by brandonros** [comment]
you mean trace in x64dbg where flag is being set?

**Comment by sha0coder** [comment]
Duncan told me that is possible to trace the flags with x64dbg, trace file or something like that.
we can implement tracing flags on scemu in similar way and do a flag diff.

**Comment by sha0coder** [comment]
trace recording saves the flags in x64dbg.

**Comment by brandonros** [comment]
before shrd

![image](https://user-images.githubusercontent.com/8949910/193345781-02c69fcb-7154-4462-9494-febcee770629.png)


after shrd

![image](https://user-images.githubusercontent.com/8949910/193345802-892642fd-5cb1-4142-8733-9b31b59835b4.png)


i can not tell if it is mov or shrd setting zf 0 / pf 0

**Comment by sha0coder** [comment]
mov don't affect any flag

**Comment by sha0coder** [comment]
last column is flags right? scemu should have --flags is very important to do well the flags, is the core.

**Comment by sha0coder** [comment]
It's emulating 100,531,806 instructions of Babushka crypter, it fails because API checks not by asm/flags.
With Mars stealer it emulates 11,318,689 instructions and then needs an API not implemented.
so main flags should be ok, but is good to verify them.

vmprotect triggering undefined behaviors, the flag behavior is also undefined regarding the manual.

**Comment by sha0coder** [comment]
![undefined](https://user-images.githubusercontent.com/1431618/193426555-fd85d9e9-06cf-444f-965a-68b867895413.png)

**Comment by sha0coder** [comment]
![calc_flags](https://user-images.githubusercontent.com/1431618/193426643-b783fee0-3a02-45ac-9e84-187f4943885d.png)

**Comment by sha0coder** [comment]
>> i can not tell if it is mov or shrd setting zf 0 / pf 0

mov don't modify flags.
the result of that shrd (4f43) is not zero, so 0->SF  And last byte (43) %2 is 1 so  0->PF

**Comment by brandonros** [comment]
all fixed, moving on
