### ISSUE TITLE
suggestion: kernel impl

### ISSUE THREAD

**Issue by darknessxk** [sha0coder/scemu#3]
In some time this git will have any kind of fully kernel emulation or something like that?

Ik this is a lot more deep but it will be a lot interesting to have or know if it will happen or not sometime

Thanks for your time reading my suggestion!

**Comment by sha0coder** [comment]
Hello, 

malware could call directly syscalls, so i should implement some of them if I see them on common malware.

Regarding full emulating kernel for example for emulating drivers or whole system, probably not in this project.

But Its a nice idea i don't know if nowadays emulation speed allows to have a scheduler with processes but would be very nice.

regards.
