### ISSUE TITLE
Error in make process

### ISSUE THREAD

**Issue by carouselcarousel** [sha0coder/scemu#37]
When I do make after the git clone:

cargo build --release
    Updating crates.io index
error: no matching package named `libscemu` found
location searched: registry `crates-io`
required by package `scemu v0.5.2 (/root/Downloads/scemu/target/release/scemu)`
make: *** [Makefile:2: all] Error 101

**Comment by sha0coder** [comment]
libscemu is on crates.io, it should install it from there automatically.
I updated it to use libscemu 0.10.5.

in linux compiles, I will test it on windows later.
~/s/scemu ❯❯❯ cargo build --release
    Finished release [optimized] target(s) in 0.02s

**Comment by sha0coder** [comment]
It should find the lib here https://crates.io/crates/libscemu 
other option is downloading the lib and setting path in Cargo.toml of scemu:
```
#ibscemu = "0.10.5"
libscemu = { path = "/home/sha0/src/libscemu/" 
```

**Comment by sha0coder** [comment]
try cargo update
